from typing import Protocol, Any


class LLMAdapter(Protocol):
    def summarize_jd(self, jd_text: str) -> dict: ...
    def improve_greeting(self, greeting: str, context: dict) -> str: ...
    def improve_cover_letter(self, cover_letter: str, context: dict) -> str: ...
    def rewrite_resume_bullet(self, bullet: str, context: dict) -> str: ...
    def explain_score(self, scores: dict, job_data: dict) -> str: ...
