"""STATUS.md generator for the Job Application OS.

Reads the state directory (containing .job-state.json and subdirectories
for predictions, packs, etc.) and produces a human-readable STATUS.md
summarizing pipeline health.

Usage::

    from jobos.status import update_status
    md = update_status("/path/to/project")
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


# Pipeline stages in order
STAGES = ["imported", "scored", "predicted", "packed", "submitted", "retro"]


# ---------------------------------------------------------------------------
# State loading
# ---------------------------------------------------------------------------

def _load_state(state_dir: Path) -> Dict[str, Any]:
    state_file = state_dir / ".job-state.json"
    if not state_file.exists():
        return {"jobs": {}, "active_rubric": "unknown", "rubric_history": []}
    return json.loads(state_file.read_text(encoding="utf-8"))


def _classify_jobs(jobs: Dict[str, Any]) -> Dict[str, List[Dict[str, Any]]]:
    """Group jobs by their current stage."""
    buckets: Dict[str, List[Dict[str, Any]]] = {s: [] for s in STAGES}
    for job_id, job in jobs.items():
        stage = job.get("status", "imported")
        if stage not in buckets:
            stage = "imported"
        entry = {"job_id": job_id, **job}
        buckets[stage].append(entry)
    return buckets


def _count_predictions(state_dir: Path) -> int:
    """Count prediction JSON files in predictions/ subdir."""
    pred_dir = state_dir / "predictions"
    if not pred_dir.is_dir():
        return 0
    return len(list(pred_dir.glob("*.json")))


def _count_packs(state_dir: Path) -> int:
    """Count application pack files in packs/ subdir."""
    pack_dir = state_dir / "packs"
    if not pack_dir.is_dir():
        return 0
    return len(list(pack_dir.glob("*")))


def _recent_activity(jobs: Dict[str, Any], limit: int = 5) -> List[Dict[str, str]]:
    """Return the most recently updated jobs, newest first."""
    entries: List[Dict[str, Any]] = []
    for job_id, job in jobs.items():
        timestamp = job.get("updated_at") or job.get("captured_at") or ""
        entries.append({
            "job_id": job_id,
            "company": job.get("company", "?"),
            "title": job.get("title", "?"),
            "status": job.get("status", "imported"),
            "timestamp": timestamp,
        })
    entries.sort(key=lambda e: e["timestamp"], reverse=True)
    return entries[:limit]


def _pending_retros(jobs: Dict[str, Any]) -> List[Dict[str, str]]:
    """Submitted jobs that lack retro data."""
    pending: List[Dict[str, str]] = []
    for job_id, job in jobs.items():
        if job.get("status") != "submitted":
            continue
        retro = job.get("retro")
        if not retro or not retro.get("outcome_label"):
            pending.append({
                "job_id": job_id,
                "company": job.get("company", "?"),
                "title": job.get("title", "?"),
                "submitted_at": job.get("updated_at") or job.get("submitted_at") or "",
            })
    return pending


# ---------------------------------------------------------------------------
# Markdown generation
# ---------------------------------------------------------------------------

def _render_table(headers: List[str], rows: List[List[str]]) -> str:
    """Render a simple Markdown table."""
    col_widths = [len(h) for h in headers]
    for row in rows:
        for i, cell in enumerate(row):
            col_widths[i] = max(col_widths[i], len(cell))

    def _fmt_row(cells: List[str]) -> str:
        parts = []
        for i, cell in enumerate(cells):
            parts.append(cell.ljust(col_widths[i]))
        return "| " + " | ".join(parts) + " |"

    separator = "|" + "|".join("-" * (w + 2) for w in col_widths) + "|"
    lines = [_fmt_row(headers), separator]
    for row in rows:
        lines.append(_fmt_row(row))
    return "\n".join(lines)


def _build_status_md(
    state_dir: Path,
    state: Dict[str, Any],
    buckets: Dict[str, List[Dict[str, Any]]],
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    jobs = state.get("jobs", {})
    total = len(jobs)
    active_rubric = state.get("active_rubric", "none")
    rubric_history: List[Dict[str, Any]] = state.get("rubric_history", [])

    lines: List[str] = []
    lines.append("# STATUS.md")
    lines.append("")
    lines.append(f"> Auto-generated by `jobos.status.update_status`")
    lines.append(f"> Last updated: {now}")
    lines.append("")

    # -- Pipeline counts --
    lines.append("## Pipeline")
    lines.append("")
    rows = [[s.capitalize(), str(len(buckets[s]))] for s in STAGES]
    rows.append(["**Total**", f"**{total}**"])
    lines.append(_render_table(["Stage", "Count"], rows))
    lines.append("")

    # -- Predictions & packs (filesystem counts) --
    pred_count = _count_predictions(state_dir)
    pack_count = _count_packs(state_dir)

    # -- Opportunities --
    opportunities = state.get("opportunities", [])
    if opportunities:
        lines.append("## Opportunities")
        lines.append("")
        # Group by verdict
        by_verdict: Dict[str, List[Dict[str, Any]]] = {}
        for opp in opportunities:
            v = opp.get("verdict", "unknown")
            by_verdict.setdefault(v, []).append(opp)
        for verdict in ("feasible", "clean", "suspect", "high-risk", "scam", "unknown"):
            opps = by_verdict.get(verdict, [])
            if opps:
                opp_rows = [
                    [opp.get("category", "?"), opp.get("name", "?"), opp.get("verdict", "?"), opp.get("status", "candidate")]
                    for opp in opps
                ]
                lines.append(_render_table(["Category", "Name", "Verdict", "Status"], opp_rows))
                lines.append("")

    # -- Active opportunity --
    active_opp = state.get("active_opportunity")
    if active_opp:
        lines.append("## Active Opportunity")
        lines.append("")
        if isinstance(active_opp, dict):
            name = active_opp.get("opportunity_name", active_opp.get("name", "?"))
            lines.append(f"- **Name:** {name}")
            if active_opp.get("verification_first_step"):
                lines.append(f"- **Next step:** {active_opp['verification_first_step']}")
            if active_opp.get("expected_income_range"):
                lines.append(f"- **Income range:** {active_opp['expected_income_range']}")
        lines.append("")
    if pred_count or pack_count:
        lines.append("## Artifacts")
        lines.append("")
        lines.append(f"- Predictions on disk: **{pred_count}**")
        lines.append(f"- Application packs on disk: **{pack_count}**")
        lines.append("")

    # -- Pending retros --
    pending = _pending_retros(jobs)
    lines.append("## Pending Retros")
    lines.append("")
    if pending:
        retro_rows = [
            [p["job_id"], p["company"], p["title"], p["submitted_at"]]
            for p in pending
        ]
        lines.append(_render_table(
            ["Job ID", "Company", "Role", "Submitted"], retro_rows,
        ))
    else:
        lines.append("_none_")
    lines.append("")

    # -- Active rubric --
    lines.append("## Rubric")
    lines.append("")
    lines.append(f"- **Active version:** `{active_rubric}`")
    if rubric_history:
        lines.append(f"- **History:** {len(rubric_history)} prior version(s)")
        for entry in rubric_history[-3:]:
            v = entry.get("version", "?")
            ts = entry.get("bumped_at", "?")
            lines.append(f"  - `{v}` -- {ts}")
    lines.append("")

    # -- Recent activity --
    recent = _recent_activity(jobs)
    lines.append("## Recent Activity")
    lines.append("")
    if recent:
        activity_rows = [
            [r["job_id"], r["company"], r["title"], r["status"], r["timestamp"]]
            for r in recent
        ]
        lines.append(_render_table(
            ["Job ID", "Company", "Role", "Status", "Last Updated"],
            activity_rows,
        ))
    else:
        lines.append("_no activity yet_")
    lines.append("")

    # -- Jobs by stage (detail sections) --
    lines.append("## Jobs by Stage")
    lines.append("")
    for stage in STAGES:
        entries = buckets[stage]
        lines.append(f"### {stage.capitalize()} ({len(entries)})")
        lines.append("")
        if entries:
            detail_rows = [
                [e["job_id"], e.get("company", "?"), e.get("title", "?")]
                for e in entries
            ]
            lines.append(_render_table(["ID", "Company", "Role"], detail_rows))
        else:
            lines.append("_none_")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def update_status(state_dir: str | Path) -> str:
    """Generate STATUS.md from the state directory and return the Markdown.

    Args:
        state_dir: Path to the project root containing ``.job-state.json``.

    Returns:
        The generated Markdown string (also written to ``STATUS.md``).
    """
    state_dir = Path(state_dir)
    state = _load_state(state_dir)
    buckets = _classify_jobs(state.get("jobs", {}))
    md = _build_status_md(state_dir, state, buckets)

    output_path = state_dir / "STATUS.md"
    output_path.write_text(md, encoding="utf-8")
    return md
